<a href="https://colab.research.google.com/github/Hanz-Zoe/AI-Studies/blob/main/tensorflow_mockup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("Tensorflow Version: ", tf.__version__)

Tensorflow Version:  2.15.0


# Loading a new Dataset
Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


# CREATING A MACHINE LEARNING MODEL


Build a
```
#  tf.keras.Sequential :
```
model



In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[1:]).numpy()
predictions

array([[ 0.35843375, -0.35822287,  0.62400895, ..., -0.6297127 ,
         0.5346486 ,  0.06903816],
       [ 0.3547577 , -0.16184098,  0.01098055, ..., -0.20584613,
        -0.24253286,  0.11363522],
       [ 0.19185078, -0.91868156,  0.14247087, ..., -0.5608319 ,
         0.32419914, -0.47749677],
       ...,
       [ 0.00432061,  0.19780609,  0.39019126, ..., -0.42410395,
        -0.09417187, -0.25496402],
       [ 0.5498585 , -0.02843705,  0.73739254, ..., -0.40799013,
         0.05407141, -0.02771793],
       [ 0.08518894, -0.57582325,  0.9904036 , ..., -0.52617395,
         0.18016513, -0.3678282 ]], dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:

In [6]:
tf.nn.softmax(predictions).numpy()
#converts all of the arrays values into probabilites, we can use this to make the AI predict and make decisions based on these probabilities.

array([[0.14061095, 0.0686719 , 0.18338211, ..., 0.05234468, 0.16770586,
        0.10527766],
       [0.15512355, 0.09253835, 0.10999607, ..., 0.08855449, 0.08536459,
        0.12188761],
       [0.14448576, 0.04759123, 0.13752435, ..., 0.06806739, 0.16493134,
        0.07398285],
       ...,
       [0.11162063, 0.13544849, 0.16418217, ..., 0.07272472, 0.10115091,
        0.08612686],
       [0.1511227 , 0.08475769, 0.18229498, ..., 0.05798843, 0.09204752,
        0.08481867],
       [0.11451149, 0.05912554, 0.28312537, ..., 0.06213518, 0.12592056,
        0.07279578]], dtype=float32)

In [13]:
#making the loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
##  The loss function takes a vector of ground truth values and a vector of logits
##  and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.
##  This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.


Clique duas vezes (ou pressione "Enter") para editar

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2999 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1410 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1065 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0855 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0743 - accuracy: 0.9772


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0708 - accuracy: 0.9782 - 821ms/epoch - 3ms/step


[0.07084019482135773, 0.9782000184059143]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.0105153e-07, 1.9585869e-08, 1.6893779e-05, 6.0763926e-04,
        2.5833823e-12, 4.4399837e-07, 3.0446735e-14, 9.9937207e-01,
        5.3203036e-07, 1.7146182e-06],
       [2.7703772e-08, 7.4561667e-06, 9.9998653e-01, 4.7749877e-06,
        1.9658435e-13, 1.2550572e-06, 3.4271245e-08, 1.3926550e-13,
        3.1141951e-08, 7.7840573e-12],
       [3.6054797e-07, 9.9682742e-01, 5.7597109e-04, 3.5854759e-05,
        1.3767557e-04, 2.9926773e-06, 2.0656387e-05, 1.8967465e-03,
        4.9840152e-04, 4.0275904e-06],
       [9.9954540e-01, 1.6817959e-08, 4.2264038e-04, 2.4238250e-07,
        3.2078219e-06, 1.9508263e-06, 1.3314922e-05, 2.7674603e-06,
        4.8588692e-08, 1.0259686e-05],
       [2.3697000e-06, 2.2406563e-09, 4.3291516e-07, 2.5574911e-08,
        9.9206960e-01, 4.0970585e-07, 7.3754086e-07, 1.8995868e-05,
        2.6394528e-06, 7.9048676e-03]], dtype=float32)>